### ISSUE TITLE
[BUG] Save Manager no longer shows local saves

### ISSUE THREAD

**Issue by robertearrey** [FSGModding/FSG_Mod_Assistant#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening the Save Manager there are no saves showing up and there is a warning log. Game launches successfully and able to login to saves

### Expected Behavior

Able to see current local saves and duplicate backups.

### Environment

```markdown
- Mod Assistant Version: Current Version
- OS: Windows 11 Pro
- Virtualized: No
```

### Anything else?

2024-12-05 01:21:28 | WARNING | mod-cache >> Invalid Mod Cache (old), resetting.
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:37 | WARNING | savegame-manager >> XML Parse error or default key not found farms.xml :: farms
2024-12-05 01:22:37 |  DANGER | render-savemanage >> Unhandled Rejection
2024-12-05 01:22:37 | WARNING | render-savemanage >> farms is not iterable
2024-12-05 01:22:37 | WARNING | render-savemanage >> TypeError: farms is not iterable
 --     at stateManager.doFarms (file:///C:/Users/rober/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/savemanage_ui.js:135:27)
 --     at stateManager.doTemplate (file:///C:/Users/rober/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/savemanage_ui.js:111:24)
 --     at stateManager.processData (file:///C:/Users/rober/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/savemanage_ui.js:80:28)
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: careerSavegame.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> Could Not Open XML File :: farms.xml :: Error: File-Manager File-Not-Found
2024-12-05 01:22:42 | WARNING | savegame-manager >> XML Parse error or default key not found farms.xml :: farms
2024-12-05 01:22:42 |  DANGER | render-savemanage >> Unhandled Rejection
2024-12-05 01:22:42 | WARNING | render-savemanage >> farms is not iterable
2024-12-05 01:22:42 | WARNING | render-savemanage >> TypeError: farms is not iterable
 --     at stateManager.doFarms (file:///C:/Users/rober/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/savemanage_ui.js:135:27)
 --     at stateManager.doTemplate (file:///C:/Users/rober/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/savemanage_ui.js:111:24)
 --     at stateManager.processData (file:///C:/Users/rober/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/savemanage_ui.js:80:28)

**Comment by jtsage** [comment]
indeed.  this is fixed in the current dev builds, and will be finished for next release.  thanks
